config/routes.rb
Rails.application.routes.draw do

  root 'users#show'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  resources :users, only: [:show] do
    resources :credit_lines, only: [:show, :new, :create, :destroy] do
      get 'transactions_form'
      post 'draw'
      post 'pay'
      get 'get_monthly_bill'
      get 'move_back_date'
      resources :transactions, only: [:index]
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_one :credit_line, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize, only: [:show]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  def show
    @user = current_user
    @credit_line = @user.credit_line
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for @user, url: '/users' do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  Name: <%= f.text_field :name %>
  <br>
  Email: <%= f.text_field :email %>
  <br>
  Password: <%= f.password_field :password %>
  <br>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <br>
  <%= f.submit "Submit" %>

<% end %>

app/views/users/show.html.erb
<h2>User Details</h2>
<div id="user_details" >
  <h4>Name: <%= @user.name %></h4>
  <h5>Email: <%= @user.email %></h5>  
</div>
<br>
<div id="account_details" >
  <% if @credit_line.present? %>
    <%= render 'credit_lines/show' %>
    <%= link_to "Delete Credit Line", user_credit_line_path({credit_line_id: @credit_line.id, user_id: @user.id}), method: :delete,
                                  data: { confirm: "You sure?" } %>
    <br>
    <br>
    <% if @credit_line.check_interest_payment_day? %>
      <%= form_tag user_credit_line_get_monthly_bill_path({credit_line_id: @credit_line.id, user_id: @user.id}), method: :get do %>
        <%= submit_tag 'Get Monthly Bill' %>
      <% end %>
    <% end %>
    <br>
    <%= link_to "Withdraw", user_credit_line_transactions_form_path( { category: 'draw', credit_line_id: @credit_line.id, user_id: @user.id}) %>
    <br>
    <%= link_to "Pay", user_credit_line_transactions_form_path( { category: 'pay', credit_line_id: @credit_line.id, user_id: @user.id}) %>
    <br>
    <br>
    <h4><%= link_to "Show Transactions", user_credit_line_transactions_path(@user,@credit_line) %></h4>
    <%= form_tag user_credit_line_move_back_date_path({credit_line_id: @credit_line.id, user_id: @user.id}), method: :get do %>
      <%= submit_tag 'Moveback credit start date' %>
    <% end %>
  <% else %>
    <div id="create_account" >
      <span>Create Account </span><%= link_to 'Create', new_user_credit_line_path(@user) %>
    </div>
  <% end %>
</div>