config/routes.rb
Rails.application.routes.draw do

  root 'users#show'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  resources :users, only: [:show] do
    resources :credit_lines, only: [:show, :new, :create, :destroy] do
      get 'transactions_form'
      post 'draw'
      post 'pay'
      get 'get_monthly_bill'
      get 'move_back_date'
      resources :transactions, only: [:index]
    end
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :authorize
  def index
    @transactions = Transaction.where(credit_line_id: params[:credit_line_id])
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def transaction_type(category)
    case category
    when 'draw'
      'credit'
    when 'pay'
      'debit'
    when 'interest'
      'interest'
    else
      'undefined'
    end
  end

  def status(value)
    return value ? 'passed' : 'failed'
  end
end

app/views/transactions/index.html.erb
<h3>Transactions</h3>

<table>
  <tr>
    <th>Date</th>
    <th>Amount</th>
    <th>Type</th>
    <th>Passed/Failed</th>
  </tr>
  <% @transactions.each do |transaction| %>
    <tr>
      <td><%= transaction.transaction_date.strftime("%m/%d/%Y") %></td>
      <td><%= transaction.amount.round(2) %></td>
      <td><%= transaction_type(transaction.category) %></td>
      <td><%= status(transaction.good) %></td>
    <tr>
  <% end %>
</table>
<p><%= link_to "Back to account details", user_path(current_user) %><p>